start:
  target:
    entity:
      integration: stopwatch_plus
    device:
      integration: stopwatch_plus

pause:
  target:
    entity:
      integration: stopwatch_plus
    device:
      integration: stopwatch_plus

reset:
  target:
    entity:
      integration: stopwatch_plus
    device:
      integration: stopwatch_plus

toggle:
  target:
    entity:
      integration: stopwatch_plus
    device:
      integration: stopwatch_plus
